web:
    build: .
    environment:
        - PHP_FPM_USE_SOCKET=1
        - PHP_FPM_SOCKET_PATH=/var/php-fpm/run/php-fpm.sock
        - PHP_FPM_PM_MAX_CHILDREN=10
        - PHP_FPM_PM_MAX_REQESTS=100
        - PHP_FPM_PM_START_SERVERS=2
        - PHP_FPM_PM_MIN_SPARE_SERVERS=1
        - PHP_FPM_PM_MAX_SPARE_SERVERS=2
        - PHP_FPM_REQUEST_TERMINATE_TIMEOUT=30
        - PHP_INI_REGISTER_GLOBALS=On
        - PHP_INI_POST_MAX_SIZE=256M
        - PHP_INI_MAX_INPUT_TIME=60
        - PHP_INI_MAX_EXECUTION_TIME=300
        - PHP_INI_DATE_TIMEZONE=Europe/Kiev
    volumes:
        - /path/to/project/on/host:/path/to/project/on/container
        - /path/to/store/socket/on/host:/var/php-fpm/run
